<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Chọn danh mục' => '',
    'Chọn huyện' => '',
    'Chọn hình ảnh' => '',
    'Chọn sản phẩm' => '',
    'Chọn tỉnh' => '',
    'Di động' => '',
    'Giá' => '',
    'Hạn đăng tin' => '',
    'Ngày bắt đầu' => '',
    'Ngày kết thúc' => '',
    'Nhập từ khóa' => '',
    'Thông tin chi tiết' => '',
    'Tiêu đề' => '',
    'Tên liên hệ' => '',
    'Đơn vị tính' => '',
    'Địa chỉ' => '',
    'Chọn ngày' => '@@@@',
    'Email' => '@@@@',
    'Hình ảnh' => '@@@@',
    'Thời tiết ngày khác' => '@@@@',
    'Từ ngày' => '@@@@',
    'Đến ngày' => '@@@@',
];
